import type {Metadata} from "next";
import {Inter, Poppins} from "next/font/google";
import "./globals.css";
import AppFooter from "@/app/_components/AppFooter";
import React from "react";
import {CircuitBackground} from "@/app/(home)/_components/CircuitBackground";
import Link from "next/dist/client/link";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
})

const poppins = Poppins({
    variable: "--font-poppins",
    subsets: ["latin"],
    weight: ['100']
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.variable} ${poppins.variable} antialiased min-h-screen relative`}>
        {/* CPU Background */}
        <CircuitBackground/>
        {/* Floating Boxes */}
        <div className="fixed inset-0 -z-10 bg-cover bg-center">
            <ul className="circles">
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
                <li></li>
            </ul>
        </div>

        <header className=" bg-white/80 backdrop-blur-sm sticky top-0 z-50">
            <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
                <h1 className="font-semibold text-2xl">mogau_im.</h1>
                <nav className="hidden md:flex items-center gap-8">
                    <a href="#home" className="text-gray-700 hover:text-black transition-colors">Home</a>
                    <a href="#about" className="text-gray-700 hover:text-black transition-colors">About</a>
                    <a href="#projects" className="text-gray-700 hover:text-black transition-colors">Projects</a>
                    <a href="#stack" className="text-gray-700 hover:text-black transition-colors">Tech Stack</a>
                    <a href="#experience" className="text-gray-700 hover:text-black transition-colors">Experience</a>
                </nav>
                <Link target="_blank" href="https://quillqode.com"
                      className="bg-yellow-300 hover:bg-yellow-400 px-4 py-2 rounded transition-colors font-bold">
                    Quill Qode
                </Link>
            </div>
        </header>

        {children}

        <AppFooter/>
        </body>
        </html>
    );
}
